### ISSUE TITLE
There is  no train_script.py in this project

### ISSUE THREAD

**Issue by Carolingliang** [EleutherAI/gpt-neox#104]
![image](https://user-images.githubusercontent.com/78017166/106249439-556ad280-624d-11eb-9c20-7055319b0c7e.png)
There is  no train_script.py in this project

**Comment by srulikbd** [comment]
yeah it's a bit confusing, we need to change the doc.
the meaning is for example for scripts like: 'train_enwik8.py' or 'train.py' etc.

**Comment by StellaAthena** [comment]
Hi @Carolingliang! @srulikbd is correct. I haven’t put a lot of effort into the README because the code structure is actively under development, but to run the code substitute your desired training script (we provide `train_enwik8.py` and `train.py`, the later of which uses the Enron Emails dataset) for `train_script.py`.
