### ISSUE TITLE
ModuleNotFoundError: No module named 'deepspeed.ops.op_builder' on import deepspeed

### ISSUE THREAD

**Issue by shankyemcee** [EleutherAI/gpt-neox#425]
Getting this error on import of deepspeed. I am currently using torch 1.8.0 and installed the requirements.txt as directed. I am also not able to install the apex link provided.

**Comment by EricHallahan** [comment]
It would be of great assistance if you could provide more detail about the nature of the issue. What is your environment? What steps can we take to reproduce? We ask that you follow the [Issue template for bug reports](https://github.com/EleutherAI/gpt-neox/blob/3ce4dba16c3ebcd0f16d5fb5e1566cf3d760180d/.github/ISSUE_TEMPLATE/bug_report.md), as it specifies the information we are interested in.

**Comment by EricHallahan** [comment]
I must note that <kbd>pip install torch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0</kbd> installs PyTorch wheels [retrieved from PyPi](https://pypi.org/project/torch) and not [retrieved from PyTorch directly](https://download.pytorch.org/whl/torch_stable.html). I also see that the APEX install says that you have installed the CPU version of PyTorch, which seems to conflict with other information I have (both installing from PyPi and your own words). By following that trail I was able to replicate the issue with APEX install with `torch==1.8.0+cpu`.

I therefore recommend installing PyTorch as outlined in the [PyTorch Getting Started guide](https://pytorch.org/get-started/locally/). In your case that would be <kbd>pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html</kbd> (alternatively any of the CUDA 11.1 builds of PyTorch since 1.8 will do). If this gives you trouble, install CUDA toolkit 11.1 for the installation of DeepSpeed, APEX and the Megatron kernels, as if my memory serves me right APEX will complain and installation will fail if the CUDA toolkit version does not match the one used to build PyTorch.

**Comment by shankyemcee** [comment]
Thanks I followed your instructions for installing torch directly from PyTorch without changing my nvidia toolkit and I'm not getting the previous error anymore. But now I'm getting the error that the triton version is not available.:

ERROR: Could not find a version that satisfies the requirement triton==0.4.2 (from deepspeed) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0)
ERROR: No matching distribution found for triton==0.4.2 (from deepspeed)

I am using python 3.8.0 and updated my pip version as well.

**Comment by StellaAthena** [comment]
> To answer your questions, yes I am currently trying to run gpt-neox on windows. But that's just for testing if the model is working for my use case, I plan to later on run on a cloud compute server called computeCanada, which I'm sure I'll run into problems with as well later.
> 
> How do I install deepspeed excluding triton? I am getting this error when trying to install deepspeed. git+git://github.com/EleutherAI/DeeperSpeed.git@c45ec1c0ac05803c02763d7e43be67919e475a2c#egg=deepspeed

Windows is a nightmare and you shouldn’t be trying to install things on it to test.
