### ISSUE TITLE
Skipped 50 iterations in a row due to Overflow - Exiting training.

### ISSUE THREAD

**Issue by ScTof** [EleutherAI/gpt-neox#482]
**Describe the bug**
Hi, I'm getting an error trying to follow the "Quick Start" guide (https://github.com/EleutherAI/gpt-neox#quick-start):
Skipped 50 iterations in a row due to Overflow - Exiting training.

The error comes about after checkpoint global_step90000 is created. This is the traceback:

Traceback (most recent call last):
  File "train.py", line 27, in <module>
    pretrain(neox_args=neox_args)
  File "\~/gpt-neox/megatron/training.py", line 103, in pretrain
    iteration = train(
  File "\~/gpt-neox/megatron/training.py", line 562, in train
    overflow_monitor.check(skipped_iter)  # check for repeated overflow
  File "\~/gpt-neox/megatron/utils.py", line 353, in check
    raise Exception(
Exception: Skipped 50 iterations in a row due to Overflow - Exiting training.

**To Reproduce**
1. I'm using an Anaconda environment with Python 3.8.12 and PyTorch 1.10.0 (configured for GPU).
2. I executed the following two commands from the repository root:
pip install -r requirements/requirements.txt
python ./megatron/fused_kernels/setup.py install

3. Then I downloaded preconfigured datasets by executing:
python ./prepare_data.py

4. Afterwards I got the enron data by running:
python prepare_data.py enron -t CharLevelTokenizer -d ./data/

5. Finally, I ran the pretraining module as:
python ./deepy.py train.py -d configs small.yml local_setup.yml

I didn't make any changes to the pre-existing config files.

Could somebody tell me what I'm doing wrong? Thanks in advance!

**Comment by pwstegman** [comment]
I ran into a similar issue in the past. Are the model weights in the latest checkpoint very large? It might be that the weights are shooting way up and causing overflows. Adding L2 regularization can help prevent this. In small.yml, you can change [line 56](https://github.com/EleutherAI/gpt-neox/blob/207caf6fc3d40a5cdb124b3ac6920ccb7cbfa5c6/configs/small.yml#L56) to:

```yml
"weight-decay": 0.01
```

I'm not sure if this will override the value in the checkpoint though.

**Comment by StellaAthena** [comment]
90,000 steps is a lot for a dataset as small as Enron. You're doing multiple epochs and the model is diverging. I recommend using weight decay set to `0.1` or even higher if you want to train this model to completion. In general, I recommend using weight decay unless you've deduplicated your data.

Perhaps this was a bad idea, but the quick start was not particularly intended to be run as-is for all 320,000 steps. That would be nearly 10 epochs on the Enron data which is quite excessive and not likely to produce a particularly good model. We used Enron in the demo because it's small and therefore can be downloaded and tokenized quickly, rather than because it's a good starter dataset.

What would you like to see in the quick start guide? Any advice about how to stop others from falling into this pitfall would be appreciated.

**Comment by sdtblck** [comment]
This is not a bug - this is completely intended behaviour. 

The configs in this repo are not necessarily ready to go, depending on your dataset / model configuration you'll need to do tuning, they're just there for example purposes. I suggest you have a read of how [mixed precision training works](https://docs.nvidia.com/deeplearning/performance/mixed-precision-training/index.html). 

Stella made some good points, another thing you can try is to change the dynamic loss scaling parameters.

**Comment by ScTof** [comment]
@StellaAthena @pwstegman Thanks for your helpful feedback. The program is currently running with a weight decay of 0.15. So far no errors, let's see if it terminates.

@StellaAthena You asked what I would like to see in the quick start. What would be helpful, is a pre-created config file that works well with the given dataset and is referenced in the quick start guide. Basically, design the guide in a way that it can be followed blindly to train a first model.
