### ISSUE TITLE
`error: pathspec 'make_fused_kernels_optional' did not match any file(s) known to git.`

### ISSUE THREAD

**Issue by Mather10** [EleutherAI/gpt-neox#575]
How to fix the error below

`error: pathspec 'make_fused_kernels_optional' did not match any file(s) known to git.`

when running "git checkout make_fused_kernels_optional"? Thanks.

**Comment by StellaAthena** [comment]
There is no branch by that name, as it has been merged into the main branch already.

**Comment by StellaAthena** [comment]
You have opened a large number of issues asking for help with extremely basic concepts over the past week. While we are happy to help where possible, this is a research codebase aimed at experts in deep learning. Additionally, responding to questions about the codebase takes time away from otherwise busy researchers.

If your question can be easily answered via a Google search (as almost every question you’ve asked so far can be), it is not a good use of anyone’s time to post it here.

You have been warned in the EleutherAI discord server that it is not an appropriate place to ask basic questions about python or GitHub. Consider this your second warning: further questions of this sort on GitHub or in the discord server will result in you being banned from both.
