### ISSUE TITLE
Could remove useless tokens

### ISSUE THREAD

**Issue by bellard** [EleutherAI/gpt-neox#585]
In the gpt-neox 20B tokenizer there are 23 special tokens containing only spaces which are always used when the input contains at least 2 consecutive spaces. So the 221 normal tokens which contain at least two consecutive spaces are never used and could be removed.

**Comment by StellaAthena** [comment]
You are not wrong, but removing them will not do anything as the tokenizer’s size is primarily determined by efficiency calculations rather than the actual number of tokens one “needs.” Most tokenizers are actually padded with dummy tokens for this reason (I don’t recall off the top of my head if ours is)
