### ISSUE TITLE
Clarification for initializations between Gpt-J and Gpt-Neox

### ISSUE THREAD

**Issue by gupta-abhay** [EleutherAI/gpt-neox#603]
The [whitepaper](http://eaidata.bmk.sh/data/GPT_NeoX_20B.pdf) published states that the feed-forward output layers before residuals follow the Gpt-J implementation for weight initialization. 

Looking at the [mesh-transformer-jax](https://github.com/kingoflolz/mesh-transformer-jax/blob/master/mesh_transformer/layers.py#L253) implementation for this, the code seems to use TruncatedNormal distribution, whereas the initialization mechanism in this [repo](https://github.com/EleutherAI/gpt-neox/blob/581e4fe1f0060e0a2797c55f640fa8bfde3d6644/megatron/model/init_functions.py#L98) uses the Normal distribution. 

I wanted to clarify if the discrepancy is largely due to the fact that pytorch does not have native support for truncated_normal distribution - or is there any other reason for this?

**Comment by StellaAthena** [comment]
You are correct that this is an additional difference, thank you for pointing it out!

This was not done for any particular reason... a combination of PyTorch not having native support for the truncated normal distribution and us not noticing the difference (the people who did most of the coding on GPT-NeoX were not involved with the coding of GPT-J). We have also uncovered a second small difference due to a bug in our implementation, namely that the layernorms are _untied_ whereas in GPT-J they are tied. This is documented in [the current arXiv preprint](https://arxiv.org/abs/2204.06745) and I will make a note to make this difference documented there as well.

**Comment by gupta-abhay** [comment]
Thanks for clarifying.
