### ISSUE TITLE
Gibberish text generation after converting to Huggingface.

### ISSUE THREAD

**Issue by kanwatchara-k** [EleutherAI/gpt-neox#712]
Hi,
I am having trouble converting my checkpoints to Huggingface format. The model works fine when using Deepspeed + Megatron ([example](https://colab.research.google.com/drive/1_WACopUywhLU7ZzjulD2i_UrGUfoTAux?usp=sharing])). 
```
generate_samples_from_prompt(neox_args, model, ['สวัสดีครับ' for i in range(1)],temperature=0.9, top_k=40)
>>  {'context': 'สวัสดีครับ', ## means 'hello'
  'text': 'เพื่อนๆครับ มีเพื่อนๆ คนไหนที่ทำงานแล้ว หรือกำลังทำงานแล้ว แล้วได้ลาออกจากงานไปแล้วแต่ยังหางานอยู่บ้างครับ พอดีอยากทราบวิธีหางานหรือแนะนำบริษัท ที่ให้เงินเดือนดี และน่าเชื่อถือหน่อยครับ'}
```

However, it becomes gibberish when converted into Huggingface format ([example](https://colab.research.google.com/drive/1ydZJJxZvFohRs7p4KBM7QgswJvgl4_Ye?usp=sharing)).
```
pipe = TextGenerationPipeline(model, tok, device=0)
pipe("สวัสดีครับ",max_new_tokens=50, top_k=40,do_sample=True, temperature=0.9)
>>  [{'generated_text': 'สวัสดีครับ ค.. ดี. แรง 1-". และทำ<|endoftext|>'}]
```

I have tried multiple conversion scripts so far (e.g., [this](https://github.com/EleutherAI/gpt-neox/pull/701/files#diff-fff7e2d700e82c3e6027c575c1cd96830ba839ff44fa6b82abf2cb21b029d55c) and [this](https://github.com/EleutherAI/gpt-neox/tree/multilingual-ko/tools/convert_to_hf)) without success.

All the related files (weights, config, and tokenizer) are in [my google drive](https://drive.google.com/drive/u/1/folders/1rE-Ucu6NC3d8hd1_EjLtdPC1U-E20FJR). 

Any help is greatly appreciated!

**Comment by StellaAthena** [comment]
@haileyschoelkopf

**Comment by haileyschoelkopf** [comment]
Oh, @kanwatchara-k  would you be willing to send what the exact command you ran to run https://github.com/EleutherAI/gpt-neox/pull/701/files#diff-fff7e2d700e82c3e6027c575c1cd96830ba839ff44fa6b82abf2cb21b029d55c was? There’s a chance that your discrepancy is due to my current script not accepting multiple config files like you used for training.

**Comment by kanwatchara-k** [comment]
@haileyschoelkopf Of course. Though I did make some changes to the code (the modified version is [here](https://drive.google.com/file/d/154KrzPNLWYVBffGCjYeB5LViY1SpG_Rj/view?usp=sharing)). To be specific, I hard-coded the vocab file path and the tokenizer type. I also combined the two config files in the code (with the paths also hard-coded).

With the modified code, I just ran the command
`
python tools/convert_to_hf.py --input_dir checkpoints/global_step300000/ --output_dir ./
`


Thanks

**Comment by haileyschoelkopf** [comment]
Thank you!! I’ll try this to convert your checkpoint as soon as I can, hopefully later today or early tomorrow!

**Comment by haileyschoelkopf** [comment]
Still working on finding the possible issue here--I'll keep you posted!

**Comment by haileyschoelkopf** [comment]
@kanwatchara-k so sorry for the delay on my end. What fixed the issue on my end, where I had a model that also had this problem, was:

1. `pip install --upgrade transformers` to the latest version, to include this PR: https://github.com/huggingface/transformers/pull/18695
2. changing `config.json` in the HF model to have `use_parallel_residual: false`

The issue here was that your and my models which wouldn't convert properly use a layer setup different from GPT-NeoX-20b, which is controlled by `gpt_j_residual: true` in the 20b config file. Hope this helps and works for you!

**Comment by kanwatchara-k** [comment]
@haileyschoelkopf Thank you so much! It works properly now!
