### ISSUE TITLE
ModuleNotFoundError upon trying to import deepspeed

### ISSUE THREAD

**Issue by SmArtKar** [EleutherAI/gpt-neox#744]
**Describe the bug**
Getting the following `ModuleNotFoundError` upon trying to import deepspeed. Using Python 3.8.10 on Windows 10
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Artemy\AppData\Local\Programs\Python\Python38\lib\site-packages\deepspeed\__init__.py", line 7, in <module>
    from . import ops
  File "C:\Users\Artemy\AppData\Local\Programs\Python\Python38\lib\site-packages\deepspeed\ops\__init__.py", line 1, in <module>
    from . import adam
  File "C:\Users\Artemy\AppData\Local\Programs\Python\Python38\lib\site-packages\deepspeed\ops\adam\__init__.py", line 1, in <module>
    from .cpu_adam import DeepSpeedCPUAdam
  File "C:\Users\Artemy\AppData\Local\Programs\Python\Python38\lib\site-packages\deepspeed\ops\adam\cpu_adam.py", line 9, in <module>
    from ..op_builder import CPUAdamBuilder
ModuleNotFoundError: No module named 'deepspeed.ops.op_builder`

**To Reproduce**
1. Clone the repo
2. Install requirements
3. Attempt to launch deepy.py / import deepspeed

**Environment (please complete the following information):**
- Configs: Using the merged 20B config

**Additional context**
I managed to find another issue with the same content but sadly it was completely useless as it was closed with words "Windows is hell"

**Comment by StellaAthena** [comment]
I have no idea how to make this run on Windows. Have you tried WSL? What operating constraints require you to use windows?

**Comment by BjornTheProgrammer** [comment]
> > I have no idea how to make this run on Windows. Have you tried WSL? What operating constraints require you to use windows?
> 
> so just as helpful as last time, gotcha.

May I recommend using docker? You can pass commands from the terminal into the docker container. It is basically a virtualized operating system, as such it won't have any compilation issues etc. Additionally, if you have Nvidia GPUs, it is easy to pass them off to the docker container.

In my experience oftentimes it is quite literally impossible to properly set up cross-platform development environments for programs as complicated as this, even from one distribution of Linux to another.

If you insist on using windows, theoretically it might be possible, but since python libraries (especially for machine learning) are written in c/c++ and compiled to be used on the specific OS/hardware, you might find yourself being stuck in a situation where you have to compile a bunch of libraries which are dependencies to this project on your system. Even then it might not work.

Sometimes there are ways around it though, for example, I was just gonna see if I could get the python dependencies working on my M1 MacBook for fun, and I got this error.

`error: Cannot find 'mpi.h' header. Check your configuration!!!`

So I had to search which c/c++ library I had to install for it to be usable on my mac. Here is what I found...
`brew install mpich`
`whereis mpicc`
`env MPICC=/opt/homebrew/bin/mpicc pip install -r requirements/requirements.txt`

However, just after fixing this issue, I got another error
`ERROR: Failed building wheel for DyNet`

Looking in the traceback I found this line
`clang: error: the clang compiler does not support '-march=native'`

Solving this issue would require me to edit the compilation flags of the python library to use `-mcpu=apple-m1` instead.

You can see how it gets complicated quickly, and often times is just not worth it. Without docker, the only real solution to implement something like this for people's real-world use cases is to ship out machines preinstalled with all the software.

Developers only have so much time on their hands, and they can't solve issues with other dependencies easily. I have some ongoing GitHub pull requests for fixes in some modules that I use for another project, which I have been waiting for three months to be merged despite all the code being just three lines, and the reviewer stating that they would merge it after some very minor tweaks.

Realize that it just isn't feasible sometimes and that many people are doing this as something almost like charity work. Use the solutions that they have provided when possible, especially if there do not appear to be any major drawbacks.
