### ISSUE TITLE
Officially Support AMD GPUs

### ISSUE THREAD

**Issue by Quentin-Anthony** [EleutherAI/gpt-neox#954]
Currently, AMD GPU support lives experimentally in https://github.com/EleutherAI/gpt-neox/compare/main...AMD

We should port the kernel guards in https://github.com/microsoft/Megatron-DeepSpeed/commit/b4d4a0e06577218a21abf18eb7d8088bb8ecaad3#diff-059209398b62b21e2524b387fc6fd23ded28ec725798322c266ee4246d253670 to gpt-neox and bring this into `main`

- [x] Test latest gpt-neox `main` on AMD GPUs with fused kernels set to `false`
- [x] Port fused kernels to AMD hardware and test them on AMD GPUs
- [x] Add conditional HIP guards so that the same fused kernel code can run on AMD and NVIDIA GPUs without modification
- [x] Add flash-attn fallbacks because 2.x is not yet supported there

**Comment by R0n12** [comment]
Will take a look at this!

**Comment by R0n12** [comment]
- [ ] Flash-Attention-2 detection code
- [ ] All fused-kernels build passed with MI250X+ROCm5.6.0 without HIP guards and `fused_rotary_positional_embedding`
- [ ] `fused_rotary_positional_embedding` build on AMD GPUs
- [ ] Adding HIP guards to generalize building process for AMD and NVIDIA GPUs

Do we still need to detect flash attention 1 at this point since AMD has already ported their version 2? (https://github.com/ROCmSoftwarePlatform/flash-attention)

Branch: https://github.com/R0n12/gpt-neox-fork/tree/lang/amd
Based on: https://github.com/EleutherAI/gpt-neox/tree/AMD

**Comment by Quentin-Anthony** [comment]
> Do we still need to detect flash attention 1 at this point since AMD has already ported their version 2?
No I think we can drop this.

**Comment by R0n12** [comment]
Status Update: Been busy with life things recently, will get a new clean branch pushed out by next week.

**Comment by Quentin-Anthony** [comment]
Done! Great work @R0n12
