### ISSUE TITLE
input decoding error on the args string of train.py

### ISSUE THREAD

**Issue by nevakrien** [EleutherAI/gpt-neox#977]
when passing in a string that seems valid a decoding error will be raised with no explanation as to what formating the string should be or what went wrong. 

```
(neox_toolkit) user@user-System-Product-Name:~/Desktop/coder reaserch/gpt-neox$ python train.py --megatron_config /Desktop/coder_reaserch/gpt-neox/tester_stuff/megatronutf8.yml --deepspeed_config /Desktop/coder_reaserch/gpt-neox/tester_stuff/local.yml

Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    neox_args = NeoXArgs.consume_neox_args()
  File "/home/user/Desktop/coder reaserch/gpt-neox/megatron/neox_arguments/arguments.py", line 424, in consume_neox_args
    base64.urlsafe_b64decode(args_parsed.megatron_config).decode("utf-8")
  File "/home/user/anaconda3/envs/neox_toolkit/lib/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/home/user/anaconda3/envs/neox_toolkit/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (61) cannot be 1 more than a multiple of 4
``` 
I have traced it back to two libraries which are argparse and base64 and as far as I can tell are part of the base cpython implementation so I cant change those, the python I have is 3.8.16  other than those two libraries nothing touches the string at all 
from my own debuging I saw that when I pass a string without a / at the start the ```base64.urlsafe_b64decode``` method errors but when there is a / it resolves and the ```decode("utf-8")``` call errors instead

**Comment by StellaAthena** [comment]
Can you share what the string is? Ideally copy-pasted exactly as it is in your document.

My first try to resolve issues like this is simply to manually retype the offending string by hand. Often times it’s an encoding issue that may not even be visually apparent on you system.

**Comment by nevakrien** [comment]
as you can see above the input string that is implicated is the varible for ```--megatron_config``` 
which is the string ```/Desktop/coder_reaserch/gpt-neox/tester_stuff/megatronutf8.yml```

**Comment by haileyschoelkopf** [comment]
```
reaserch/gpt-neox$ python train.py --megatron_config /Desktop/coder_reaserch/gpt-neox/tester_stuff/megatronutf8.yml --deepspeed_config /Desktop/coder_reaserch/gpt-neox/tester_stuff/local.yml
```
this terminal snippet seems to imply you're using `python train.py` to launch the library yourself--is this correct?

If so, the required way to use the GPT-NeoX library for training is via `python ./deepy.py train.py /Desktop/coder_reaserch/gpt-neox/tester_stuff/megatronutf8.yml` .

**Comment by nevakrien** [comment]
oh your right sorry for the bothering you 

if you don't mind explaining whats actually going on there? I am not sure I tried understanding the manipulation happening on the input strings for ages and I got nothing.

**Comment by haileyschoelkopf** [comment]
From what I recollect, there are two things:

1. `deepy.py` handles certain distributed features and commandline arguments to the library, such as running the `deepspeed` launcher (multinode, if using multiple machines).
2. The megatron config (which isn't precisely the same as the NeoX yml file, and is in JSON format) is encoded in [Base64](https://en.wikipedia.org/wiki/Base64), resulting in something that looks a bit like a random string of characters being passed to `--megatron_config` and `--deepspeed_config`. See this line for where it happens (done by `deepy.py`). <https://github.com/EleutherAI/gpt-neox/blob/2534e3d76e320aba095894e7dc2a4b416a1ac8df/megatron/neox_arguments/arguments.py#L566C40-L566C40> This helps fix errors that arise when using slurm to launch jobs, since slurm may error when characters like `"` or comments in the YML file are included.
